name: Feature Branch
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

permissions:
  id-token: write
  contents: read

jobs:
  ci-test:
    runs-on: ubuntu-latest
    needs: [ ci-docker-build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: KengoTODA/actions-setup-docker-compose@main

      - name: Run Tests
        shell: bash
        run: |
          cd test
          ./test.sh

      - name: Cleanup
        if: always()
        shell: bash
        run: |
          cd test
          docker-compose -f down  

  ci-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ci-readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
    with:
      filter-mode: nofilter
      suggestions: false

  ci-codeowners:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
    with:
      is_fork: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

  ci:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
    needs: [ ci-docker-build, ci-docker-test, ci-readme, ci-codeowners ]