name: Main Branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  ci-readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
    with:
      filter-mode: nofilter
      suggestions: false

  ci-codeowners:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
    with:
      is_fork: false
    secrets:
      github_access_token: ${{ secrets.github_access_token }}

  controller-release:
    uses: cloudposse/github-actions-workflows/.github/workflows/controller-release.yml@releases
    needs: [ ci-readme, ci-codeowners ]

  controller-promote:
    uses: cloudposse/github-action-docker-promote@0.1.1
    with:
      registry: hub.docker.com
      login: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
      repository: ${{ github.repository }}
      from: sha-${{ github.sha }}
      to: test
      use_metadata: false
    needs: [ controller-release ]