name: tag-pushed

on:
  push:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  ci-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if tag belongs to the latest major release or is higher
        id: check_tag
        run: |
          highest_tag=$(git tag -l | grep -E "^\d+\.\d+\.\d+$" | sort -rV | head -n1)
          highest_major=$(echo "$highest_tag" | cut -d '.' -f 1)
          current_tag="${{ github.ref }}"
          current_major=$(echo "$current_tag" | cut -d '.' -f 1)
          
          if [ $current_major -ge $highest_major ]; then
            echo "is_latest_major=true" >> $GITHUB_OUTPUT
          else
            echo "is_latest_major=false" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ steps.check_tag.outputs.is_latest_major }}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}